# Site settings
title: Pierre-Olivier Goffard
email: pierre.olivier.goffard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All you need to know about me and my research work!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://LaGauffre.github.io" # the base hostname & protocol for your site
github_username:  LaGauffre
facebook_username: Pierro.goffard
twitter_username: LaGauffreBzh
#linkedIn_username:

# Build settings
markdown: redcarpet
